[book]
authors = ["Gabor Szabo"]
language = "en"
src = "src"
title = "mdBook Maven"
description = "Everything I know about mdBook that you might also want to know."


# Add github icon to the menu
[output.html]
git-repository-url = "https://github.com/szabgab/mdbook.code-maven.com"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/szabgab/mdbook.code-maven.com/edit/main/{path}"

# Remove the printer icon from the menu
[output.html.print]
enable = false

# Handle Youtube video embedding and the footer
[preprocessor.embedify]
footer.enable = true
footer.message = "Copyright © 2025 • Created with ❤️  by [Gábor Szabó](https://szabgab.com/)"

[preprocessor.alerts]



[preprocessor.preprocessor]
command = "python3 my_preprocessor.py"

#[preprocessor.jupyter_notebook]
#command = "python3 convert_jupyter_notebooks.py"


# jupyter nbconvert --to markdown src/examples/demo.ipynb --output-dir src/notebooks/


#[output.linkcheck]
#follow-web-links = true
#traverse-parent-directories = false
#user-agent = "Tester"
#optional = true

#[output.linkcheck.http-headers]
#'crates\.io' = ["Accept: text/html"]



# This requires the print.html file which will not be created as we set the output.html.print to false.
# [output.pdf]




# [output.pandoc.profile.pdf]
# output-file = "output.pdf"
# to = "latex"
